name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.24.0
  - mlflow=1.14.1
  - pip:
      - wandb
      - git+https://github.com/rebeccajohnson88/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
